# Generated by Django 3.1.2 on 2021-06-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.TextField(verbose_name='Comment:'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name:'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name:'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_in',
            field=models.TimeField(verbose_name='From:'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_out',
            field=models.TimeField(verbose_name='To:'),
        ),
    ]
