# Generated by Django 3.1.2 on 2021-06-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_auto_20210616_1308'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
    ]
