# Generated by Django 3.1.2 on 2021-06-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_historicalappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
        ),
    ]
