# Generated by Django 3.1.2 on 2021-06-16 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_changelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogs',
            name='date_logged',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
