# Generated by Django 3.1.2 on 2021-06-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_changelogs_date_logged'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table=None,
        ),
    ]
