# Generated by Django 3.1.2 on 2021-06-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0009_auto_20210616_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChangeLogs',
            new_name='ChangeLog',
        ),
    ]
